name: Lint Terraform

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  terraform-lint:
    name: Terraform Lint & Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.0
          terraform_wrapper: false

      - name: Init (no backend)
        run: terraform init -backend=false -reconfigure

      - name: Format check
        run: terraform fmt -recursive -check

      - name: Validate
        run: terraform validate -no-color
